name: Hugo Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Variáveis de configuração
      - name: Set up variables
        run: |
          HUGO_VERSION="0.140.0"
          HUGO_TAR="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
          HUGO_URL="https://github.com/EdneiFNeto/PacakgesPublic/releases/download/v${HUGO_VERSION}/${HUGO_TAR}"
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_ENV
          echo "HUGO_TAR=${HUGO_TAR}" >> $GITHUB_ENV
          echo "HUGO_URL=${HUGO_URL}" >> $GITHUB_ENV

      # Baixar o Hugo
      - name: Download Hugo
        run: |
          echo "Baixando Hugo versão $HUGO_VERSION..."
          curl -L -o $HUGO_TAR $HUGO_URL

      # Verificar se o download foi bem-sucedido
      - name: Verify download
        run: |
          if [ ! -f $HUGO_TAR ]; then
            echo "Erro: O arquivo de download não foi encontrado!"
            exit 1
          fi

      # Extrair e mover o Hugo para /usr/local/bin
      - name: Install Hugo
        run: |
          echo "Extraindo e instalando Hugo..."
          tar -xvzf $HUGO_TAR
          sudo mv hugo /usr/local/bin/

      # Verificar a versão do Hugo
      - name: Verify Hugo installation
        run: hugo version

      # Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Construir o site com Hugo
      - name: Build site
        run: |
          echo "Construindo o site com Hugo..."
          cd documentation && hugo --minify

      # Fazer upload dos artefatos
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/public

      # Limpar arquivos desnecessários
      - name: Cleanup
        run: |
          echo "Limpando arquivos temporários..."
          rm -f $HUGO_TAR
