name: Hugo Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Hugo v0.140.0 from public repo
        run: |
          # Baixar o arquivo tar.gz do Hugo do seu repositório publico
          curl -L -o hugo_0.140.0_Linux-64bit.tar.gz https://github.com/EdneiFNeto/PacakgesPublic/releases/download/v0.140.0/hugo_0.140.0_Linux-64bit.tar.gz

      - name: Verify download
        run: |
          # Verificar se o arquivo foi baixado corretamente
          if [ ! -f hugo_0.140.0_Linux-64bit.tar.gz ]; then
            echo "Erro: o arquivo de download não foi encontrado!"
            exit 1
          fi

      - name: Extract tar.gz file
        run: |
          # Extrair o arquivo tar.gz
          tar -xvzf hugo_0.140.0_Linux-64bit.tar.gz

      - name: Move Hugo to /usr/local/bin
        run: |
          # Mover o binário do Hugo para o diretório /usr/local/bin
          sudo mv hugo /usr/local/bin/

      - name: Check Hugo version
        run: |
          # Verificar se o Hugo foi instalado corretamente
          hugo version

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Hugo
        run: cd documentation && hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '${{github.workspace}}/documentation/public'

      - name: Clean up
        run: |
          # Limpar os arquivos desnecessários
          rm -f hugo_0.140.0_Linux-64bit.tar.gz
