name: Hugo Server

on:
  workflow_dispatch: # Permite executar o workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Hugo
      - name: Install Hugo
        run: |
          HUGO_VERSION=0.118.2  # Substitua pela versão desejada
          wget wget https://github.com/gohugoio/hugo/releases/download/v0.140.0/hugo_0.140.0_Linux-64bit.tar.gz
          tar -xvzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      # Rodar o servidor Hugo
      # - name: Run Hugo server
      #   run: |
      #     nohup hugo server --bind=0.0.0
