name: Hugo Server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup configuration variables
      - name: Set up variables
        run: |
          HUGO_VERSION="0.140.0"
          HUGO_TAR="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
          HUGO_URL="https://github.com/EdneiFNeto/PacakgesPublic/releases/download/v${HUGO_VERSION}/${HUGO_TAR}"
          echo "HUGO_VERSION=${HUGO_VERSION}" >> $GITHUB_ENV
          echo "HUGO_TAR=${HUGO_TAR}" >> $GITHUB_ENV
          echo "HUGO_URL=${HUGO_URL}" >> $GITHUB_ENV

      # Download Hugo
      - name: Download Hugo
        run: |
          echo "Downloading Hugo version $HUGO_VERSION..."
          curl -L -o $HUGO_TAR $HUGO_URL

      # Verify the download was successful
      - name: Verify download
        run: |
          if [ ! -f $HUGO_TAR ]; then
            echo "Error: The downloaded file was not found!"
            exit 1
          fi

      # Extract and move Hugo to /usr/local/bin
      - name: Install Hugo
        run: |
          echo "Extracting and installing Hugo..."
          tar -xvzf $HUGO_TAR
          sudo mv hugo /usr/local/bin/

      # Verify Hugo installation
      - name: Verify Hugo installation
        run: hugo version

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Build the site with Hugo
      - name: Build site
        run: |
          echo "Building the site with Hugo..."
          cd documentation && hugo --minify

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/public

      # Clean up temporary files
      - name: Cleanup
        run: |
          echo "Cleaning up temporary files..."
          rm -f $HUGO_TAR
