name: Hugo Server

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download hugo version v0.140.0
        run: |
          wget https://github.com/EdneiFNeto/PacakgesPublic/releases/download/v0.140.0/hugo_0.140.0_Linux-64bit.tar.gz
         
      - name: Extract tar.gz file
        run: |
          tar -xvzf hugo_0.140.0_Linux-64bit.tar.gz

      - name: Move files to local bin
        run: |
          sudo mv hugo /usr/local/bin/

      - name: Check version hugo
        run: |
           hugo version
