name: Download Hugo action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set the Hugo version
      - name: Set Hugo version
        run: echo "HUGO_VERSION=0.140.0" >> $GITHUB_ENV

      # Download Hugo binary
      # - name: Download Hugo binary
      #   run: |
      #     mkdir -p documentation
      #     curl -L -o documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

      # Verify Hugo binary exists
      - name: Verify tar gz
        run: ls -lh documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

      # Extract Hugo binary
      - name: Extract Hugo binary
        run: |
          tar -xzvf documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C documentation
          ls -lh documentation

      # Verify Hugo version
      - name: Verify Hugo version
        run: documentation/hugo version

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Build the site with Hugo
      - name: Build site
        run: |
          echo "Building the site with Hugo..."
          cd documentation && ./hugo --minify

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/public

      # Clean up temporary files
      - name: Cleanup
        run: |
          echo "Cleaning up temporary files..."
          rm -f documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
