on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.140.0 
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fazer o checkout do outro repositório onde o arquivo .tar.gz está localizado
      - name: Checkout other repository
        uses: actions/checkout@v4
        with:
          repository: EdneiFNeto/myDependency # Substitua pelo nome correto do repositório
          token: ${{ secrets.GITHUB_TOKEN }}     # Acesse repositórios privados com token se necessário
          path: EdneiFNeto/HugoDownloadDependency/tree/main/documentation
          
      # Extract Hugo binary
      - name: Extract Hugo binary
        run: |
          tar -xzvf documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C documentation
          ls -lh documentation

      # Verify Hugo version
      - name: Verify Hugo version
        run: documentation/hugo version

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Build the site with Hugo
      - name: Build site
        run: |
          echo "Building the site with Hugo..."
          cd documentation && ./hugo --minify

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '${{github.workspace}}/documentation/public'

      # Clean up temporary files
      - name: Cleanup
        run: |
          echo "Cleaning up temporary files..."
          rm -f documentation/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
